# Usa a imagem oficial do PostgreSQL. A tag 'alpine' é uma versão leve.
FROM postgres:13-alpine

# Define as variáveis de ambiente para o banco de dados de desenvolvimento/produção.
# ATENÇÃO: Em um ambiente de produção real, use Docker Secrets ou variáveis de ambiente injetadas para a senha.
ENV POSTGRES_USER=ellis_user
ENV POSTGRES_PASSWORD=ellis_pass
ENV POSTGRES_DB=ellis_db

# O diretório /docker-entrypoint-initdb.d é um local especial na imagem do Postgres.
# Qualquer script .sh ou .sql colocado aqui será executado na primeira vez que o container for iniciado para inicializar o banco.
COPY db_scripts/init.sql /docker-entrypoint-initdb.d/
COPY db_scripts/seed.sql /docker-entrypoint-initdb.d/
