# Usa uma imagem base oficial do Python.
FROM python:3.12-alpine

# Define variáveis de ambiente para otimizar a execução do Python em containers.
# PYTHONDONTWRITEBYTECODE: Impede o Python de criar arquivos .pyc.
# PYTHONUNBUFFERED: Garante que a saída do Python seja enviada diretamente para o terminal.
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Define o diretório de trabalho dentro do container.
WORKDIR /app

# Copia e instala as dependências primeiro para aproveitar o cache de camadas do Docker.
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copia todo o código da aplicação para o diretório de trabalho no container.
COPY . .

# Define o comando padrão para executar os testes com pytest e gerar um relatório de cobertura.
CMD ["pytest", "tests/", "--cov=api", "--cov-report", "term-missing", "--junitxml=report.xml"]