services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app/api 
    container_name: ellis_api

  tests:
    build:
      context: .
      dockerfile: Dockerfile.tests
    volumes:
      - ./api:/app/api
      - ./tests:/app/tests
    container_name: ellis_tests