# prometheus.yml

global:
  scrape_interval: 15s # Define o intervalo de coleta de métricas

scrape_configs:
  - job_name: 'api'
    static_configs:
      - targets: ['api:8000'] # Informa ao Prometheus para coletar do serviço 'api' na porta 8000